### ISSUE TITLE
Playbook doesn't run

### ISSUE THREAD

**Issue by Fail-Unsafe** [mrlesmithjr/docker-ansible-phpipam#1]
It seems as if the phpipam-entrypoint.yml playbook is never executed. I added a debug task to this playbook. It should have created a file under /tmp but didn't.

Since I moved the creation of cronjob from playbook.yml (called from the Dockerfile) to phpipam-entrypoint.yml, nothing happens.

**Comment by mrlesmithjr** [comment]
Are you rebuilding (`docker build`) the image and using that to spin up your container after making changes to the playbooks? Or are you editing the playbooks and then just doing `docker run`?

**Comment by Fail-Unsafe** [comment]
I forked your repo, made the adjustments and then built a new image by executing `docker build`.

**Comment by mrlesmithjr** [comment]
Can you share with me your changes so I can try to figure it out? I have not seen this from my side

**Comment by Fail-Unsafe** [comment]
Added some variables:
https://github.com/Fail-Unsafe/docker-ansible-phpipam/blob/master/Dockerfile

Parameterized and moved the cronjobs to
https://github.com/Fail-Unsafe/docker-ansible-phpipam/blob/master/config/ansible/phpipam-entrypoint.yml

**Comment by mrlesmithjr** [comment]
You need to modify the following in your `docker-entrypoint.sh`:

From:
```bash
ansible-playbook -i "localhost," -c local /phpipam-entrypoint.yml \
  --extra-vars "phpipam_db_host=$PHPIPAM_DB_HOST phpipam_db_name=$PHPIPAM_DB_NAME \
  phpipam_db_pass=$PHPIPAM_DB_PASS phpipam_db_user=$PHPIPAM_DB_USER"
```

To:
```bash
ansible-playbook -i "localhost," -c local /phpipam-entrypoint.yml \
  --extra-vars "phpipam_db_host=$PHPIPAM_DB_HOST phpipam_db_name=$PHPIPAM_DB_NAME \
  phpipam_db_pass=$PHPIPAM_DB_PASS phpipam_db_user=$PHPIPAM_DB_USER \
  discoverycheck_min=$DISCOVERY_MIN pingcheck_min=$PINGCHECK_MIN resolveip_min=$RESOLVEIP_CHECK"
```

Without these parameters passed to Ansible my assumption would be that the actual playbook fails on the Docker run which you could probably see by looking at the Docker logs for the container.

**Comment by Fail-Unsafe** [comment]
No difference, the output of docker logs is

`failunsafe@srv-hv-113:~/docker-ansible-phpipam$ sudo docker logs dockeransiblephpipam_web_1

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Updating APK Cache] ******************************************************`

That's it.

**Comment by mrlesmithjr** [comment]
Here is what I just saw using your repo as an FYI:
```bash
web_1  | ok: [localhost]
web_1  |
web_1  | TASK [Checking If DB Tables Exist] *********************************************
web_1  | changed: [localhost]
web_1  |
web_1  | TASK [Importing phpIPAM Schema] ************************************************
web_1  | skipping: [localhost]
web_1  |
web_1  | TASK [Adding Cron Job For discoveryCheck] **************************************
web_1  | fatal: [localhost]: FAILED! => {"failed": true, "msg": "'discoverycheck_min' is undefined"}
web_1  |
web_1  | NO MORE HOSTS LEFT *************************************************************
web_1  | 	to retry, use: --limit @/phpipam-entrypoint.retry
web_1  |
web_1  | PLAY RECAP *********************************************************************
web_1  | localhost                  : ok=7    changed=3    unreachable=0    failed=1
```

**Comment by mrlesmithjr** [comment]
So I will ask this. Would you rather me step you through how to solve your issues in your repo? Or, would you rather just let me know what functionality you would like and let me add it to this repo for you to consume? I am ok with either one, just let me know which one works better for you.

**Comment by Fail-Unsafe** [comment]
Strange, I must have made some rookie mistake. I will try to sort it out on my own. Sorry for this.

**Comment by mrlesmithjr** [comment]
And when I add the playbook example to `docker-entrypoint.sh` as mentioned above I see it executes as desired:
```bash
web_1  | ok: [localhost]
web_1  |
web_1  | TASK [Checking If DB Tables Exist] *********************************************
web_1  | changed: [localhost]
web_1  |
web_1  | TASK [Importing phpIPAM Schema] ************************************************
web_1  | skipping: [localhost]
web_1  |
web_1  | TASK [Adding Cron Job For discoveryCheck] **************************************
web_1  | changed: [localhost]
web_1  |
web_1  | TASK [Adding Cron Job For pingCheck] *******************************************
web_1  | changed: [localhost]
web_1  |
web_1  | TASK [Adding Cron Job For resolveIPaddresses] **********************************
web_1  | changed: [localhost]
web_1  |
web_1  | PLAY RECAP *********************************************************************
web_1  | localhost                  : ok=10   changed=6    unreachable=0    failed=0
```

**Comment by mrlesmithjr** [comment]
No worries at all man. I will be glad to help in anyway possible if you need it.

**Comment by Fail-Unsafe** [comment]
I've identified the initial problem: When the container starts it tries to access the internet to update the APK cache but fails due to our proxy. I've passed in the necessary environment variables by editing the docker-compose.yml file.

**Comment by mrlesmithjr** [comment]
Awesome. Glad you have identified the issue. Or at least one of them :)
