### ISSUE TITLE
ping doesn't work in interface?

### ISSUE THREAD

**Issue by cchance27** [mrlesmithjr/docker-ansible-phpipam#5]
It seems the cronjobs are working to ping, but pinging from the web interface isn't working?

**Comment by cchance27** [comment]
it seems swapping to fping and setting the fping path to /usr/sbin/fping makes it work, perhaps a way to fix that maybe just do a symlink as part of the ansible script so the defaults work, not sure about the standard ping not working maybe also because of location issue?

**Comment by mrlesmithjr** [comment]
I'll have to find some time to dig into this when time permits. But thanks for letting me know.
